{% set name = "openmmgridforce" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jimtufts/openmmgridforce/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 049b7448e18634cd5d9ef31a4e2fda68ce634db7165444c1fccba7e9095b55c6

build:
  number: 0
  skip: True  # [win or osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - swig
    - make  # [unix]
    - {{ stdlib('c') }}
  host:
    - python
    - pip
    - numpy
    - openmm >=8.0
    - setuptools
    - netCDF4
    - pytest
  run:
    - python
    - numpy
    - {{ pin_compatible('openmm', max_pin='x.x') }}

test:
  source_files:
    - python/tests
    - python/prmtopcrd
    - python/grids
  imports:
    - gridforceplugin
  requires:
    - pip
    - pytest
    - netCDF4
    - openmm
  commands:
    - pip check
    - cd python/tests && pytest test_grid_force.py test_auto_grid.py test_auto_scaling.py -v

about:
  home: https://github.com/jimtufts/openmmgridforce
  summary: 'OpenMM plugin for grid-based forces'
  description: |
    GridForce plugin for OpenMM that enables grid-based force calculations.
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jimtufts
